# Generated by Django 4.2.2 on 2023-06-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
    ]
