# Generated by Django 4.2.2 on 2023-06-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_company_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
    ]
