# Generated by Django 4.2.2 on 2023-06-23 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.job')),
            ],
        ),
    ]
