# Generated by Django 4.2.2 on 2023-06-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0009_jobskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
