# Generated by Django 4.2.2 on 2023-06-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0012_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
