# Generated by Django 4.2.2 on 2023-06-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0013_company_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_active',
        ),
    ]
