# Generated by Django 4.2.2 on 2023-06-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0014_remove_job_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_finished',
        ),
    ]
