# Generated by Django 4.2.2 on 2023-06-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0015_remove_company_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_request',
            field=models.BooleanField(default=False),
        ),
    ]
