# Generated by Django 4.2.2 on 2023-07-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0017_jobapplication_is_conform'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
