# Generated by Django 4.2.2 on 2023-07-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0021_empexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
