# Generated by Django 4.2.2 on 2023-07-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0030_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='empexperience',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
