# Generated by Django 4.2.2 on 2023-07-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0031_empexperience_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='empexperience',
            name='location',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
