# Generated by Django 4.2.2 on 2023-07-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0033_empexperience_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='empexperience',
            name='job_profile',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
