# Generated by Django 4.2.2 on 2023-07-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0034_empexperience_job_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empexperience',
            name='experience',
        ),
    ]
