# Generated by Django 4.2.2 on 2023-07-16 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0036_jobtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_app.jobtype'),
            preserve_default=False,
        ),
    ]
