# Generated by Django 4.2.2 on 2023-07-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0037_job_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
    ]
