# Generated by Django 4.2.2 on 2023-07-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0040_remove_job_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vacancies',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
