# Generated by Django 4.2.2 on 2023-07-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0041_job_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_field',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
