# Generated by Django 4.2.2 on 2023-07-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0047_company_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
    ]
