# Generated by Django 4.2.2 on 2023-07-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0049_company_website_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
