# Generated by Django 4.2.2 on 2023-07-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0050_company_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_img', models.ImageField(blank=True, upload_to='image')),
                ('emb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.job')),
            ],
        ),
    ]
