# Generated by Django 4.2.2 on 2023-07-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0051_applyjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='is_conform',
            field=models.BooleanField(default=False),
        ),
    ]
