# Generated by Django 4.2.2 on 2023-07-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0055_remove_jobapplication_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
    ]
