# Generated by Django 4.2.2 on 2023-07-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0056_remove_jobapplication_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
